default: &default
  adapter: postgresql
  encoding: utf8
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: testBot_development
test:
  <<: *default
  database: testBot_test
production:
  <<: *default
  database: testBot_production
  username: testBot
  password: <%= ENV['TESTBOT_DATABASE_PASSWORD'] %>
